// Generated by Qodo Gen

const { generateSidebarsFile } = require('../../lib/skelo-utils');
const global = require('../../lib/skelo-utils');

describe('generateSidebarsFile', () => {
    // Handles null/undefined sidebarData input
    it('should throw error when sidebarData is null', () => {
      const options = {
        sidebarsFilename: 'sidebars',
        templateExtension: '.hbs',
        templates: './templates'
      };

      expect(() => {
        generateSidebarsFile(null, options);
      }).toThrow('generateSidebarsFile: sidebarData was null or undefined.');

      expect(() => {
        generateSidebarsFile(undefined, options);
      }).toThrow('generateSidebarsFile: sidebarData was null or undefined.');
    });
});
