name: Update README.md

on:
  push:
    branches:
      - main

jobs:
  update-readme:
    runs-on: ubuntu-latest
    env:
      CLI_PATH: ./index.js

    strategy:
      matrix:
        node-version: [21.x, 22.x, 23.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install npm packages
        run: |
          npm install
          echo "npm packages installed."

      - name: Create USAGE.md
        run: |
          node generate-usage.js $CLI_PATH
          echo "USAGE.md file created by generate-usage.js."
          cat USAGE.md

      - name: Update README.md
        run: |
          if [ ! -f README.md ]; then
            echo "README.md not found. Skipping step."
            exit 0
          fi

          if [ ! -f USAGE.md ]; then
            echo "USAGE.md not found. Skipping step."
            exit 0
          fi

          CONTENT=$(cat USAGE.md)
          echo "Content of USAGE.md stored in variable CONTENT."

          TIMESTAMP="<!-- $(date) -->"
          echo "Current date and time stored in variable TIMESTAMP: $TIMESTAMP"

          CONTENT="$TIMESTAMP\n$CONTENT"
          echo "Prepended TIMESTAMP to CONTENT."

          if grep -q '<!-- INSERT:USAGE.md -->' README.md; then
            echo "Found short tag <!-- INSERT:USAGE.md -->."
            
            awk '/<!-- INSERT:USAGE.md -->/ {print "<!-- INSERT_START:USAGE.md --><!-- INSERT_END:USAGE.md -->"; next}1' README.md > temp.md && mv temp.md README.md

            echo "Short tag replaced with block tags."
          fi

          if grep -q '<!-- INSERT_START:USAGE.md -->' README.md && grep -q '<!-- INSERT_END:USAGE.md -->' README.md; then
            echo "Found block tags <!-- INSERT_START:USAGE.md --> and <!-- INSERT_END:USAGE.md -->."
            
            awk '/<!-- INSERT_START:USAGE.md -->/,/<!-- INSERT_END:USAGE.md -->/ {if (/<!-- INSERT_START:USAGE.md -->/) {print "<!-- INSERT_START:USAGE.md -->\n" content "\n<!-- INSERT_END:USAGE.md -->"; next} if (/<!-- INSERT_END:USAGE.md -->/) {next} next}1' content="$CONTENT" README.md > temp.md && mv temp.md README.md

